### ISSUE TITLE
Change default upload folder from 'files'

### ISSUE THREAD

**Issue by fri3ndly** [ckfinder/ckfinder-laravel-package#20]
In previous version of CKFinder we had it set up so that if a user clicked on the image icon and uploaded a file it would default to the 'images' folder, where as if a link was created and file uploaded this would appear in the 'files' folder.

Is this possible? At the moment everything seems to be added to 'files' by default, even when commenting out the  files resourceType config (which then breaks the upload completely)

**Comment by jswiderski** [comment]
In CKFinder 2.x when uploading through image plugin you in deed had `type=Images` parameter added when uploading and browsing e.g. 
```
Images: /ckfinder261/ckfinder.html?type=Images&CKEditor=editor1&CKEditorFuncNum=0&langCode=pl
Links: /ckfinder261/ckfinder.html?CKEditor=editor1&CKEditorFuncNum=0&langCode=pl
```

In CKFinder 3.x that paramter is gone:
```
//Links and Images 
192.168.1.100:8224/ckfinder350/ckfinder.html?CKEditor=editor1&CKEditorFuncNum=0&langCode=pl
```
----
@fri3ndly since this is a general error and not laravel specific, we will close the issue here and report it in main CKFinder repository. 

In order to work around this problem please use the manual integration: https://ckeditor.com/docs/ckfinder/ckfinder3-php/integration.html#integration_ckeditor_manual

Assuming that you are using CKEditor 4, CKFinder 3 PHP and you have CKFinder installed as main application in `xampp/htdocs/ckfinder350` you editor configuration could look like:

```
var editor = CKEDITOR.replace( 'editor1', {
	extraPlugins: 'uploadimage,image2',
	removePlugins: 'image',
	rememberLastFolder : false,
	filebrowserBrowseUrl: 'http://192.168.1.100:8224/ckfinder350/ckfinder.html',
	filebrowserImageBrowseUrl: 'http://192.168.1.100:8224/ckfinder350/ckfinder.html?type=Images',
	filebrowserUploadUrl: '/ckfinder350/core/connector/php/connector.php?command=QuickUpload&type=Files',
	filebrowserImageUploadUrl: '/ckfinder350/core/connector/php/connector.php?command=QuickUpload&type=Images', 
	language : 'en'
} );
```
Please notice the `type=Images` parameter for image upload and browse settings. You can also add `type=Files` (or `type=whateverResourceTypeYouWant`) to general upload and browse settings.

**Comment by fri3ndly** [comment]
Perfect thank you!

**Comment by jswiderski** [comment]
I have reported issue here: https://github.com/ckfinder/ckfinder/issues/398.
